config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'welocme#index'
   get "about" => "welocme#about"

   

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @pins = Pin.all
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.build
    respond_with(@pin)
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    @pin.save
    respond_with(@pin)
  end

  def update
    @pin.update(pin_params)
    respond_with(@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/controllers/welocme_controller.rb
class WelocmeController < ApplicationController

  def index
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welocme_helper.rb
module WelocmeHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-inverse red">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "ooby", root_path, class: "navbar-brand"%>
	    </div>

	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
	       <ul class="nav navbar-nav navbar-right">
	       <li><%= link_to 'About us', about_path %></li>
	        <% if user_signed_in? %>
	          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
	        <% else %>
		        <li><%= link_to "Sign in", new_user_session_path %></li>
		        <li><%= link_to "Sign up", new_user_registration_path %></li>
	        <% end %>

	      </ul>
	    </div>
	  </div>
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Interest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do|name, msg| %>
	<%= content_tag(:div, msg , class: "alert alert-warning alert-#{name}") %>
<% end %>	

<%= yield %>

</body>
</html>

app/views/pins/_form.html.erb
<div class="container">
  <%= form_for(@pin) do |f| %>
    <% if @pin.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

        <ul>
        <% @pin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div class="container">
  <h1>Listing pins</h1>

  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th>User id</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @pins.each do |pin| %>
        <tr>
          <td><%= pin.description %></td>
          <td><%= pin.user.email if current_user %></td>
          <td><%= link_to 'Show', pin %></td>
          <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
          <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Pin', new_pin_path %>
</div>

app/views/pins/new.html.erb
<div class="container">
	<h1>New pin</h1>

	<%= render 'form' %>
	<%= link_to 'Back', pins_path %>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>

app/views/welocme/about.html.erb
<div class="auto_fix">
	<%= render 'layouts/footer' %>

	<div class="container">
		

	</div>


</div>
<div class="footer">
	
</div>

app/views/welocme/index.html.erb
<div class="auto_fix">
	<%= render 'layouts/footer' %>

	<div class="container">
		

	</div>


</div>
<div class="footer">
	
</div>	